teleport-wait-time: 5
teleport-request-expire: 30
teleport-coolDown: 3

home-limit:
  default: 3
  group-name: 10

Messages:
  prefix: "&6[BHT]"
  invalid-command: "%prefix% &cIncorrect usage."
  teleport-request-sent: "%prefix% &fTeleport request sent to &3%player%&f!"
  teleport-request-received: "%prefix% &fYou have received a teleport request from &3%player%&f. Use &a/tpaccept &fto accept or &c/tpacancel &fto reject."
  teleport-request-expired: "%prefix% &fYour teleport request to &3%player%&f has expired."
  teleport-request-not-found: "%prefix% &fTeleport request not found."
  teleport-request-player-not-found: "%prefix% &cThis player is not online."
  teleport-request-accepted: "%prefix% &fYou accepted the teleport request from &3%player%&f."
  teleport-request-denied: "%prefix% &fYou denied the teleport request from &3%player%&f."
  teleport-cancelled: "%prefix% &fTeleport &ccancelled."
  teleport-wait: "%prefix% &fWait &3%time% &7seconds before executing this command."
  home-set: "%prefix% &fYour home &3%home% &fhas been set successfully!"
  home-remove: "%prefix% &fHome &3%home% &fhas been &cremoved&f."
  home-limit-reached: "%prefix% &cYou have reached the maximum home limit."
  home-visibility-changed: "%prefix% &3%home% &fis now &3%status%"
  home-visibility-public: "&apublic"
  home-visibility-private: "&cprivate"
  home-not-found: "%prefix% &fHome '&3%home%&f' not found."

Titles:
  teleporting-title: "&6Teleporting to %target%"
  teleporting-subtitle: "&fDon't move"

Menus:
  confirm-menu:
    menu-title: "Go to &3%target%?"
    menu-confirm-item-name: "&aConfirm"
    menu-cancel-item-name: "&cCancel"
  homes-menu:
    menu-title: "%player%'s homes | Page %page%/%pages%"
    menu-home-item-name: "&6%home%"
    menu-home-item-lore: "&aPosition: &f%position% \n&aWorld: &f%world% \n&aBiome: &f%biome%\n&aStatus: &f%status%"
    menu-page-item: "&aPage: &f%page&"
    menu-next-page-item: "&aNext Page"
    menu-previous-page-item: "&aPrevious Page"

    menu-item-biomes-list: #tuned to 1.20 biomes
      PLAINS: GRASS_BLOCK
      SUNFLOWER_PLAINS: GRASS_BLOCK
      FOREST: OAK_LOG
      BIRCH_FOREST: BIRCH_LOG
      OLD_GROWTH_BIRCH_FOREST: BIRCH_LOG
      DARK_FOREST: DARK_OAK_LOG
      TAIGA: SPRUCE_LOG
      SNOWY_TAIGA: SPRUCE_LOG
      GROVE: SPRUCE_LOG
      CHERRY_GROVE: CHERRY_LOG
      DESERT: SANDSTONE
      BEACH: SAND
      JUNGLE: JUNGLE_LOG
      SWAMP: SLIME_BLOCK
      JAGGED_PEAKS: STONE
      SAVANNA: ACACIA_LOG
      BADLANDS: RED_SANDSTONE
      ICE_SPIKES: PACKED_ICE
      THE_VOID: BARRIER
      #CUSTOM_BIOME: ITEM
